/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package javaapplication1.chuong3.dohoa.frame;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javaapplication1.chuong3.coffeelogic.CoffeeShop;
import javaapplication1.chuong3.coffeelogic.Manager;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author TRUNG HIEU
 */
public class MyCoffee extends javax.swing.JInternalFrame {
    Manager[] managers;
    /**
     * Creates new form MyCoffee
     */
    public MyCoffee() throws ParseException {
        initComponents();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
        
        CoffeeShop[] a = new CoffeeShop[] {new CoffeeShop("Kha Coffee", "2 Nguyen Hue"),
                                             new CoffeeShop("White garden", "4 Nguyen Hue"),
                                             new CoffeeShop("Hoang Truc Vien", "3 Nguyen Hue")};
        managers = new Manager[]{
                                new Manager(a, 1000, "Le Thi A", 0, df.parse("12-12-1999")),
                                new Manager(new CoffeeShop[]{
                                                new CoffeeShop("Hoang Hac", "12 Nguyen Hue")
                                },
                                        2000, "Nguyen Van B", 0, df.parse("12-12-2000"))};
        for (int i = 0;i < managers.length; i++){
            cbquanly.addItem(managers[i].getHoten());          
        }
        DefaultTableModel model = (DefaultTableModel) tblhienthi.getModel();
        model.setRowCount(0);
        CoffeeShop[] shops = managers[0].getShops();
        for(int i = 0; i < shops.length; i++){
            model.insertRow(model.getRowCount(), 
                    new Object[]{model.getRowCount() + 1,
                        shops[i].getName(),
                        shops[i].getAddress()});
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbquanly = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblhienthi = new javax.swing.JTable();

        setClosable(true);
        setTitle("Danh Sách Các Quán Coffee");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Ho ten nguoi quan ly");

        cbquanly.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbquanlyItemStateChanged(evt);
            }
        });

        tblhienthi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên Quán", "Địa Chỉ"
            }
        ));
        jScrollPane1.setViewportView(tblhienthi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbquanly, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbquanly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void cbquanlyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbquanlyItemStateChanged
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblhienthi.getModel();
        model.setRowCount(0);
        int index = cbquanly.getSelectedIndex();
        CoffeeShop[] shops = managers[index].getShops();
        for(int i = 0; i < shops.length; i++){
            model.insertRow(model.getRowCount(), 
                    new Object[]{model.getRowCount() + 1,
                        shops[i].getName(),
                        shops[i].getAddress()});
        }
    }//GEN-LAST:event_cbquanlyItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbquanly;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblhienthi;
    // End of variables declaration//GEN-END:variables
}
